### ISSUE TITLE
Raw input error

### ISSUE THREAD

**Issue by haxersworld** [TechnicalMujeeb/tmvenom#1]
Traceback (most recent call last):
  File "tmvenom.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 676, in <module>
  File "<string>", line 105, in main
NameError: name 'raw_input' is not defined

**Comment by Saadsaadwqqe** [comment]
اي الحل
